- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - software-properties-common
      - wget
    state: present
  retries: 5
  delay: 10
  register: apt_result
  until: apt_result is succeeded


- name: Add Grafana official GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana Repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    filename: grafana

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Start and enable Grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes