- hosts: execution-user
  become: yes
  tasks:
    - include_tasks: ../roles/monitoring-stack/tasks/docker.yaml

- hosts: execution-user
  become: yes
  tasks:
    - include_tasks: ../roles/monitoring-stack/tasks/grafana.yaml

- hosts: execution-user
  become: yes
  tasks:
    - include_tasks: ../roles/monitoring-stack/tasks/prometheus.yaml