- hosts: grafana-new-user
  become: yes
  roles:
    - ../roles/docker

- hosts: grafana-new-user
  become: yes
  roles:
    - ../roles/grafana

- hosts: grafana-new-user
  become: yes
  roles:
    - ../roles/prometheus