- hosts: execution-user
  become: yes
  roles:
    - ../roles/docker

- hosts: execution-user
  become: yes
  roles:
    - ../roles/grafana

- hosts: execution-user
  become: yes
  roles:
    - ../roles/prometheus