- hosts: root-user
  become: yes
  tasks:
  - include_tasks: ../roles/vps-configuration/tasks/createuser.yml

- hosts: root-user
  become: yes
  tasks:
  - include_tasks: ../roles/vps-configuration/tasks/harden-ssh.yml