services:
  reverse-proxy:
    image: traefik:v3.1
    container_name: traefik
    ports: 
      - "80:80"
      - "8080:8080"
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config:/config
  grafana: 
    image: grafana/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`www.verturus.com`) || Host(`verturus.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    tty: true
    stdin_open: true
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SERVICE_ACCOUNTS_ENABLED=true
    restart: on-failure
  prometheus:
    image: prom/prometheus:latest
    tty: true
    stdin_open: true
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: on-failure
    networks:
      monitoring:
        aliases:
          - bitname/prometheus

volumes:
  grafana-storage:

networks:
  monitoring:
    name: monitoring