- name: Ensure .ssh directory exists
  file: 
    path: "~/.ssh"
    state: directory
    mode: 0700

- name: Copy private key from Window
  copy:
    src: "/mnt/c/Users/Zephyr/.ssh/id_ed25519"
    dest: "~/.ssh/id_ed25519"
    mode: '0600'

- name: Copy public key from Window
  copy:
    src: "/mnt/c/Users/Zephyr/.ssh/id_ed25519.pub"
    dest: "~/.ssh/id_ed25519.pub"
    mode: '0644'
    
- name: Display success
  debug:
    msg: "SSH keys have been copied successfully!"