- name: Install Socat
  apt:
    name:
      - socat
    state: present
  retries: 5
  delay: 10
  register: apt_result
  until: apt_result is succeeded

- name: Creating socat proxy
  shell: socat TCP-LISTEN:19566,fork,reuseaddr TCP:127.0.0.1:19565 &

