name: CI workflow for updating prometheus data sources

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'vps-configuration/files/prometheus.yml'


jobs:
  update-prometheus-yml-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Copy Files from github to vps
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: vchen7629
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "vps-configuration/files/prometheus.yml"
          target: "/home/vchen7629"
          strip_components: 2

      - name: Restart Prometheus
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: vchen7629
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "${{ secrets.password }}" | sudo -S docker compose restart
     